### PR TITLE
Fix compilation when -Werror=maybe-uninitialized is enabled

### PR DESCRIPTION
**Pull request by ascillato**
## Description

The `now` struct is not initialized and the compiler complains about it when `-Werror=maybe-uninitialized` is enabled. This PR solves this by initializing the struct to zero before it is being used.

## PR checklist

Please tick as appropriate and edit the reasons (e.g.: "backport: not needed because this is a new feature")

- [x] **changelog** not required
- [x] **backport** not required
- [x] **tests** not required

## Notes for the submitter

Please refer to the [contributing guidelines](https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md), especially the checklist for PR contributors.

### CODE REVIEW

**Comment by ascillato** [comment]
Hi @mahavirj,

Please, can you take a look to this small PR? This solves an issue when trying to compile in debug mode to do memory inspect.

The error I receive is the following:

```
Building in debug mode
Compiling .pio/build/TEST/mbedtls/mbedtls/library/x509_crt.o
/home/ascillato/.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/x509_crt.c: In function 'x509_crt_verify_chain':
/home/ascillato/.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/x509_crt.c:2632:15: error: 'now' may be used uninitialized [-Werror=maybe-uninitialized]
 2632 |         ret = x509_crt_find_parent(child, cur_trust_ca, &parent,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2633 |                                    &parent_is_trusted, &signature_is_good,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2634 |                                    ver_chain->len - 1, self_cnt, rs_ctx,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2635 |                                    &now);
      |                                    ~~~~~
/home/ascillato/.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/x509_crt.c:2386:12: note: by argument 9 of type 'const mbedtls_x509_time *' to 'x509_crt_find_parent' declared here
 2386 | static int x509_crt_find_parent(
      |            ^~~~~~~~~~~~~~~~~~~~
/home/ascillato/.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/x509_crt.c:2537:23: note: 'now' declared here
 2537 |     mbedtls_x509_time now;
      |                       ^~~
/home/ascillato/.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/x509_crt.c:2684:19: error: 'now' may be used uninitialized [-Werror=maybe-uninitialized]
 2684 |         *flags |= x509_crt_verifycrl(child, parent, ca_crl, profile, &now);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ascillato/.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/x509_crt.c:2019:12: note: by argument 5 of type 'const mbedtls_x509_time *' to 'x509_crt_verifycrl' declared here
 2019 | static int x509_crt_verifycrl(mbedtls_x509_crt *crt, mbedtls_x509_crt *ca,
      |            ^~~~~~~~~~~~~~~~~~
/home/ascillato/.platformio/packages/framework-espidf/components/mbedtls/mbedtls/library/x509_crt.c:2537:23: note: 'now' declared here
 2537 |     mbedtls_x509_time now;
      |                       ^~~
cc1: all warnings being treated as errors
```

With the proposed change in this PR, this issue is fixed and the compilation runs fine.

**Comment by mahavirj** [comment]
@ascillato 

PR looks good to me. Probably you have `MBEDTLS_HAVE_TIME_DATE` disabled and hence the warning. Can you please submit this PR in the upstream mbedtls repository (https://github.com/Mbed-TLS/mbedtls/pulls)?

**Comment by ascillato** [comment]
Hi, yes, you are right. I have `MBEDTLS_HAVE_TIME_DATE` disabled which is the default in the SDK in ESP32-S3.

I will submit the PR to mainstream. Thanks for the fast answer.

**Comment by ascillato** [comment]
PR submitted to mainstream: https://github.com/Mbed-TLS/mbedtls/pull/8896

**Pull request closed without merging**
